#!/usr/bin/env python3
from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "html5" / "entities.kk"


def kk_escape_string(s: str) -> str:
    # Koka string literals are close enough to JSON for our needs.
    return json.dumps(s, ensure_ascii=True)


def main() -> int:
    # Python's stdlib html.entities.html5 is a mapping for HTML5 named entities.
    # Keys include both semicolon and some legacy non-semicolon forms.
    items = sorted(html.entities.html5.items())
    lines: list[str] = []
    lines.append("module html5/entities")
    lines.append("")
    lines.append("// Auto-generated by `tools/gen_entities_kk.py`.")
    lines.append("// Source: Python `html.entities.html5`.")
    lines.append("")
    lines.append("pub val entities : list<(string,string)> = [")
    for k, v in items:
        lines.append(f"  ({kk_escape_string(k)}, {kk_escape_string(v)}),")
    lines.append("]")
    lines.append("")
    lines.append("pub fun lookup(name: string) : maybe<string>")
    lines.append("  entities.find-maybe(fn((k,v)) if k == name then Just(v) else Nothing)")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
