#!/usr/bin/env python3
from __future__ import annotations

import html
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "html5" / "entities.kk"


_UNSAFE_CODEPOINTS: set[int] = {
    # Bidirectional control characters (often rejected by parsers for safety).
    0x061C,  # ARABIC LETTER MARK
    0x200E,  # LRM
    0x200F,  # RLM
    *range(0x202A, 0x202F),  # LRE..RLO + PDF + LRM/RLM neighbors
    *range(0x2066, 0x206A),  # LRI..PDI
    0xFEFF,  # BOM / ZWNBSP
    0x2028,  # LS
    0x2029,  # PS
}


def kk_escape_string(s: str) -> str:
    # Koka accepts UTF-8 source for non-BMP codepoints, but it rejects some
    # "unsafe" codepoints in string literals. Emit those as \uXXXX escapes.
    out: list[str] = ['"']
    for ch in s:
        cp = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif cp < 0x20 or cp in _UNSAFE_CODEPOINTS:
            out.append(f"\\u{cp:04x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main() -> int:
    # Python's stdlib html.entities.html5 is a mapping for HTML5 named entities.
    # Keys include both semicolon and some legacy non-semicolon forms.
    items = sorted(html.entities.html5.items())
    lines: list[str] = []
    lines.append("module html5/entities")
    lines.append("")
    lines.append("// Auto-generated by `tools/gen_entities_kk.py`.")
    lines.append("// Source: Python `html.entities.html5`.")
    lines.append("")
    lines.append("pub val entities : list<(string,string)> = [")
    for k, v in items:
        lines.append(f"  ({kk_escape_string(k)}, {kk_escape_string(v)}),")
    lines.append("]")
    lines.append("")
    lines.append("pub fun lookup(name: string) : maybe<string>")
    lines.append("  entities.find-maybe(fn((k,v)) if k == name then Just(v) else Nothing)")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
